[phases.setup]
nixPkgs = ['nodejs_20', 'npm-10_x', 'openssl']

[nix]
channel = "nixos-24.05"

[phases.install]
cmds = ['npm ci --legacy-peer-deps --include=dev || npm install --legacy-peer-deps --include=dev']

[phases.build]
cmds = ['rm -rf dist', 'npm run build']

[start]
cmd = 'npm start'
